const express = require(‘express’);
const PDFDocument = require(‘pdfkit’);
const path = require(‘path’);
const fs = require(‘fs’);

const app = express();
app.use(express.json());
app.use(express.static(‘public’));

// Create output directory if it doesn’t exist
const outputDir = path.join(__dirname, ‘pdfs’);
if (!fs.existsSync(outputDir)) {
fs.mkdirSync(outputDir);
}

// Generate PDF endpoint
app.post(’/api/generate-pdf’, (req, res) => {
const { title, content, author, template, color } = req.body;

// Validate input
if (!title || !content) {
return res.status(400).json({ error: ‘Title and content are required’ });
}

try {
const doc = new PDFDocument({
size: ‘A4’,
margin: 40,
});

```
const filename = `${title.replace(/\s+/g, '_')}_${Date.now()}.pdf`;
const filepath = path.join(outputDir, filename);

// Pipe to file
doc.pipe(fs.createWriteStream(filepath));

// Define colors based on template
const colors = {
  darkGold: '#b8932a',
  cream: '#f5f5f0',
  black: '#1a1a1a',
  teal: '#2d5f6f',
  maroon: '#5a2e3e',
};

const accentColor = colors[color] || colors.darkGold;
const bgColor = colors.cream;
const textColor = colors.black;

// Header with accent line
doc.fontSize(28).font('Helvetica-Bold').fillColor(textColor).text(title, {
  align: 'center',
});

doc.moveTo(70, doc.y + 5).lineTo(525, doc.y + 5).stroke(accentColor);
doc.moveDown(1);

// Author/date info
if (author) {
  doc
    .fontSize(10)
    .fillColor('#666')
    .text(`By ${author} | ${new Date().toLocaleDateString()}`, {
      align: 'center',
    });
}

doc.moveDown(2);

// Main content
doc
  .fontSize(11)
  .fillColor(textColor)
  .font('Helvetica')
  .text(content, {
    align: 'left',
    lineGap: 5,
  });

// Footer
doc.moveDown(2);
doc
  .fontSize(9)
  .fillColor('#999')
  .text('Generated by LoudMinds PDF Generator', {
    align: 'center',
  });

doc.end();

// Send file once finished writing
doc.on('finish', () => {
  res.json({
    success: true,
    filename: filename,
    downloadUrl: `/download/${filename}`,
  });
});
```

} catch (error) {
console.error(‘PDF generation error:’, error);
res.status(500).json({ error: ‘Failed to generate PDF’ });
}
});

// Download endpoint
app.get(’/download/:filename’, (req, res) => {
const filepath = path.join(outputDir, req.params.filename);

// Security check: ensure file is in output directory
if (!filepath.startsWith(path.resolve(outputDir))) {
return res.status(403).json({ error: ‘Access denied’ });
}

if (!fs.existsSync(filepath)) {
return res.status(404).json({ error: ‘File not found’ });
}

res.download(filepath);
});

// List generated PDFs
app.get(’/api/pdfs’, (req, res) => {
fs.readdir(outputDir, (err, files) => {
if (err) {
return res.status(500).json({ error: ‘Failed to read PDFs’ });
}

```
const pdfFiles = files
  .filter((f) => f.endsWith('.pdf'))
  .map((f) => ({
    name: f,
    size: fs.statSync(path.join(outputDir, f)).size,
    downloadUrl: `/download/${f}`,
  }));

res.json(pdfFiles);
```

});
});

// Cleanup old PDFs (older than 24 hours)
const cleanupOldPDFs = () => {
const maxAge = 24 * 60 * 60 * 1000; // 24 hours
const now = Date.now();

fs.readdir(outputDir, (err, files) => {
if (err) return;

```
files.forEach((file) => {
  const filepath = path.join(outputDir, file);
  const stat = fs.statSync(filepath);

  if (now - stat.mtimeMs > maxAge) {
    fs.unlinkSync(filepath);
  }
});
```

});
};

// Run cleanup every hour
setInterval(cleanupOldPDFs, 60 * 60 * 1000);

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
console.log(`PDF Generator running on http://localhost:${PORT}`);
});
